// <auto-generated />
using System;
using ClashRoyaleDataModel.DatabaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClashRoyaleDataModel.Migrations
{
    [DbContext(typeof(ClanParticipationContext))]
    [Migration("20200518072841_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("ClashRoyaleDataModel.Models.DonationRecord", b =>
                {
                    b.Property<DateTime>("StoredDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerTag")
                        .HasColumnType("TEXT");

                    b.Property<int>("Donations")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DonationsReceived")
                        .HasColumnType("INTEGER");

                    b.HasKey("StoredDate", "PlayerTag");

                    b.HasIndex("PlayerTag");

                    b.ToTable("DonationRecords");
                });

            modelBuilder.Entity("ClashRoyaleDataModel.Models.Player", b =>
                {
                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Tag");

                    b.ToTable("ClanMembers");
                });

            modelBuilder.Entity("ClashRoyaleDataModel.Models.WarLog", b =>
                {
                    b.Property<string>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CreatedDate");

                    b.ToTable("WarHistory");
                });

            modelBuilder.Entity("ClashRoyaleDataModel.Models.WarParticipation", b =>
                {
                    b.Property<string>("PlayerTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarLogDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("BattlesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionDayBattlesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfBattles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WarlogCreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerTag", "WarLogDate");

                    b.HasIndex("WarlogCreatedDate");

                    b.ToTable("WarResults");
                });

            modelBuilder.Entity("ClashRoyaleDataModel.Models.DonationRecord", b =>
                {
                    b.HasOne("ClashRoyaleDataModel.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClashRoyaleDataModel.Models.WarParticipation", b =>
                {
                    b.HasOne("ClashRoyaleDataModel.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClashRoyaleDataModel.Models.WarLog", "Warlog")
                        .WithMany("WarParticipants")
                        .HasForeignKey("WarlogCreatedDate");
                });
#pragma warning restore 612, 618
        }
    }
}
