// <auto-generated />
using ClashRoyale.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClashRoyale.Migrations
{
    [DbContext(typeof(WarParticipationContext))]
    [Migration("20200506054522_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("ClashRoyale.Models.ClanMember", b =>
                {
                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.Property<int>("Donations")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DonationsReceived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Tag");

                    b.ToTable("ClanMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
